services:
  postgres-db:
    image: postgres
    container_name: personal-postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: personaldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: personal-api
    command: python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "5678:5678"
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=1
    working_dir: /app
    depends_on:
      - postgres-db

volumes:
  postgres_data:
