name: Backend CI/CD (Render)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Create .env for tests (from GitHub Secrets)
        run: |
          {
            echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}"
            echo "APP_ENV=${{ secrets.APP_ENV }}"
            echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}"
            echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}"
            echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}"
            echo "CORS_ALLOWED_ORIGINS=${{ secrets.CORS_ALLOWED_ORIGINS }}"
            echo "CSRF_COOKIE_SECURE=${{ secrets.CSRF_COOKIE_SECURE }}"
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}"
            echo "DEBUG=${{ secrets.DEBUG }}"
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}"
            echo "SECURE_HSTS_SECONDS=${{ secrets.SECURE_HSTS_SECONDS }}"
            echo "SECURE_SSL_REDIRECT=${{ secrets.SECURE_SSL_REDIRECT }}"
            echo "SESSION_COOKIE_SECURE=${{ secrets.SESSION_COOKIE_SECURE }}"
            echo "USE_HTTPS=${{ secrets.USE_HTTPS }}"
          } >> .env

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test

  deploy:
    needs: test
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
